### ISSUE TITLE
ABORT misleads the operator

### ISSUE THREAD

**Issue by adlai** [adlai/scalpl#22]
The ABORT restart established in [#'actor:perform](https://github.com/adlai/scalpl/blob/b20b434/actor.lisp#L79-L81) does not do what the `:report` function says, and actually does terminate the actor without restarting.

Either the `:report` text should be modified to make obvious that the word "restart" is an imperative (i.e., _handler code and/or the operator must restart the actor_), or the restart must be established at a lower scope so the `:after` method is not skipped.

**Comment by adlai** [comment]
[Floyd's Honeypot](https://en.wikipedia.org/wiki/Cycle_detection#Algorithms):

- [ ] #34 insufficiently fascist phb
- [ ] adlai/chanl#8 insufficiently resolving bipartite quantiser
- [ ] fstamour/breeze#48 helpful comiseration
- [ ] adlai/is-dead-fossil#1 obtuse refuse
- [ ] zkat/chanl#38 dll landmine

**Comment by adlai** [comment]
The `:after` method is within the stack frames skipped by the restart.

from [CLHS 7.6.6.2](https://www.lispworks.com/cgi-bin/search.cgi?q=7.6.6.2),
> if `call-next-method` is called by the least specific `:around` method, the other methods are called as follows:
> -- All the `:before` methods are called, in most-specific-first order...
> -- The most specific primary method is called. Inside the body of a primary method, ... If `call-next-method` is not used, only the most specific primary method is called.
> -- All the `:after` methods are called in most-specific-last order. Their values are ignored.

To properly close this Issue, at least three steps are probably necessary:

- [x] correct the `abort` restart's textual description;
- [ ] create a new restart that resumes the actor's perform method, possibly named `continue` for convenience, although it might be preferable to avoid conflict with the standard name;
- [ ] move the following lines to a different method, possibly even on a different generic function where it could still be qualified with `:after`

https://github.com/adlai/scalpl/blob/b20b43419c339aa332c7777bc25f6f4924a23808/actor.lisp#L82-L83

**Comment by adlai** [comment]
> To properly close this Issue, at least three steps are probably necessary:
> 
> * [x]  correct the `abort` restart's textual description;

#44
